[host]
host = "0.0.0.0:3030"
host_pass = "asdf"

[web]
host = "0.0.0.0:3031"
enable_gql_playground = true

[redis]
url = "redis://redis:6379"

[general]
default_language = "aea02f71-ab0d-470e-9d0d-3577ec870e29"
timezone = "Asia/Seoul"