version: "3"

services:
  pms-backend:
    image: docker.astar.moe/pms-backend:latest
    restart: always
    volumes:
      - ./config.toml:/app/config.toml:z
      - ./log4rs.yaml:/app/log4rs.yaml:z
      - ./data:/app/data:z
      - ./log:/app/log:z
    environment: 
      DATABASE_URL: postgres://postgres:testserver@db/pms
    networks:
      - pms-backend-network
    ports:
      - "3030:3030"
      - "3031:3031"
    command:
      - diesel setup
      - diesel migration run
    depends_on:
      - "redis"
      - "db"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    networks:
      - pms-backend-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testserver
    volumes:
      - ./pg-data:/var/lib/postgresql/data:z
    networks:
      - pms-backend-network

networks:
  pms-backend-network:
    driver: bridge