version: "3"

services:
  pms-backend:
    build: .
    image: pms-backend
    restart: always
    volumes:
      - ./config.toml:/app/config.toml
      - ./log4rs.yaml:/app/log4rs.yaml
      - ./data:/app/data
      - ./log:/app/log
    environment: 
      DATABASE_URL: postgres://postgres:testserver@db/pms
    networks:
      - pms-backend-network
    ports:
      - "3030:3030"
      - "3031:3031"
    command:
      - diesel setup
      - diesel migration run
    depends_on:
      - "redis"
      - "db"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    networks:
      - pms-backend-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testserver
    networks:
      - pms-backend-network

networks:
  pms-backend-network:
    driver: overlay