name: Docker Image CI (AMD64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: pms-backend
          tag: $(date +%s)
          dockerUser: ${{ secrets.REGISTRY_USER }}
          dockerPassword: ${{ secrets.REGISTRY_PASSWORD }}
          dockerServer: ${{ secrets.REGISTRY_HOST }}
          platform: linux/amd64
